# Site settings
author: Sara Ginsburg
title: My Reactions to React and Redux
header-img: img/home-bg.png
email: sara.ginsburg.ny@gmail.com
copyright_name: Sara Ginsburg
description: > # this means to ignore newlines until "baseurl:"
  some notes about the React/Redux project
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  SaraGinsburg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
